name: Build and deploy

on:
  push:
    branches:
      - master
    paths:
      - "packages/web/**" # Only run when Gatsby code is edited

defaults:
  run:
    working-directory: "packages/web" 
jobs:
  main:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Compile to static bundle
        run: npm run build
        env: # Pass GitHub repository secrets as environment variables
          GATSBY_SANITY_ID: ${{ secrets.GATSBY_SANITY_ID }}
          GATSBY_SANITY_DATASET: ${{ secrets.GATSBY_SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Northern Virginia represent
          SOURCE_DIR: "public" # Output directory of Gatsby
